### ISSUE TITLE
WARNING:root:db thread except:timed out

### ISSUE THREAD

**Issue by 95289527** [mengskysama/shadowsocks-rm#13]
After running a long time,maybe ten hours .
The db loop while faild，but when i restart shadiowsocks by running 'supervisorctl restart shadowsocks'. It worked.Here is the error log below.

WARNING:root:db thread except:timed out
WARNING:root:db loop
Traceback (most recent call last):
  File "/www/shadowsocks/shadowsocks/dbtransfer.py", line 131, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/www/shadowsocks/shadowsocks/dbtransfer.py", line 58, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/www/shadowsocks/shadowsocks/dbtransfer.py", line 47, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
WARNING:root:db thread except:timed out
WARNING:root:db loop
Traceback (most recent call last):
  File "/www/shadowsocks/shadowsocks/dbtransfer.py", line 131, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/www/shadowsocks/shadowsocks/dbtransfer.py", line 58, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/www/shadowsocks/shadowsocks/dbtransfer.py", line 47, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
WARNING:root:db thread except:timed out

**Comment by mengskysama** [comment]
看起来像manager线程没有收到或者处理消息，我尝试重现下。

**Comment by mengskysama** [comment]
用最新的提交把日志打开，看看有没有什么错误输出？

**Comment by 95289527** [comment]
@mengskysama  我发现了问题
我用了autoban.py那个脚本 然后他过一段时间 就把127.0.0.1自己给加到iptables里面了
