### ISSUE TITLE
can't connect database

### ISSUE THREAD

**Issue by otherfish** [mengskysama/shadowsocks-rm#19]
### when i run `python servers.py :`

```
Traceback (most recent call last):
File "/root/shadowsocks/shadowsocks/dbtransfer.py", line 131, in thread_db
DbTransfer.get_instance().push_db_all_user()
File "/root/shadowsocks/shadowsocks/dbtransfer.py", line 58, in push_db_all_user
dt_transfer = self.get_servers_transfer()
File "/root/shadowsocks/shadowsocks/dbtransfer.py", line 47, in get_servers_transfer
data, addr = cli.recvfrom(1500)
timeout: timed out
```

我的数据库和manyuser不在同一台服务器上,不知道配置是否会不同

**Comment by mengskysama** [comment]
是不是manage端口被占用了，还是其他问题引起的？

**Comment by otherfish** [comment]
主要还是后端和前端的数据库字段不一致导致后端不能连接到前端
