### ISSUE TITLE
ss-panel 无法统计流量信息

### ISSUE THREAD

**Issue by RadishKin** [mengskysama/shadowsocks-rm#48]
服务可以正常运行，但是就是 不能统计流量信息
日志如下：
`Traceback (most recent call last):
  File "/var/www/../shadowsocks-rm/shadowsocks/dbtransfer.py", line 197, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/var/www/../shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
`

**Comment by tzwjkl** [comment]
+1

**Comment by zuoruizhi** [comment]
上配置文件

**Comment by zuoruizhi** [comment]
@G-g-beringei @tzwjkl
