### ISSUE TITLE
请问新版本多了一些设置怎么弄呢？

### ISSUE THREAD

**Issue by saladinxp** [mengskysama/shadowsocks-rm#49]
以前正常输入数据库等设置就没事了

今天新弄了发现提示错误，仔细一看设置多了这些设置
PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://domain/mu'
API_PASS = 'mupass'
NODE_ID = '1'
CHECKTIME = 15
# SYNCTIME = 600

错误提示如下
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 197, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 108, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1190, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
WARNING:root:db thread except:<urlopen error [Errno -2] Name or service not known>

**Comment by xianjian10** [comment]
我也遇到同样的问题，网上爬了半天文，没找到解决办法。

**Comment by zuoruizhi** [comment]
上配置文件

**Comment by zuoruizhi** [comment]
API配置是配合前端V3版本统计流量的，
注意格式，一定要在域名后加/mu     ；API_URL = 'http://域名/mu'

**Comment by saladinxp** [comment]
@zuoruizhi 主要是现在用的不是sspanel

**Comment by zuoruizhi** [comment]
@saladinxp 不是的话PANEL_VERSION=V2就好了
