### ISSUE TITLE
MU API on HTTPS server is not supported

### ISSUE THREAD

**Issue by xfoxfu** [mengskysama/shadowsocks-rm#55]
Config file:

```
PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'https://cflink.cf/mu'
API_PASS = 'dbjakwbdw'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600
```

Log:

```
2016-09-15 15:04:34:Traceback (most recent call last):
2016-09-15 15:04:34: File "/shadowsocks/shadowsocks/dbtransfer.py", line 197, in thread_push
2016-09-15 15:04:34: DbTransfer.get_instance().push_db_all_user()
2016-09-15 15:04:34: File "/shadowsocks/shadowsocks/dbtransfer.py", line 98, in push_db_all_user
2016-09-15 15:04:34: response = urllib2.urlopen(req)
2016-09-15 15:04:34: File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
2016-09-15 15:04:34: return opener.open(url, data, timeout)
2016-09-15 15:04:34: File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
2016-09-15 15:04:34: response = self._open(req, data)
2016-09-15 15:04:34: File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
2016-09-15 15:04:34: '_open', req)
2016-09-15 15:04:34: File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
2016-09-15 15:04:34: result = func(*args)
2016-09-15 15:04:34: File "/usr/local/lib/python2.7/urllib2.py", line 1241, in https_open
2016-09-15 15:04:34: context=self._context)
2016-09-15 15:04:34: File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
2016-09-15 15:04:34: raise URLError(err)
2016-09-15 15:04:34:URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
2016-09-15 15:04:34:WARNING:root:db thread except:<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

**Comment by xfoxfu** [comment]
PS: The website is on <cflink.cf> and the cert is from Letsencrypt.
