### ISSUE TITLE
运行servers.py 启动服务不起来

### ISSUE THREAD

**Issue by cdhhhhhhh** [mengskysama/shadowsocks-rm#57]
一开始老报错后来该配置文件后报这个
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 206, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 66, in push_db_all_user
    last_time = time.time()
UnboundLocalError: local variable 'time' referenced before assignment
WARNING:root:db thread except:local variable 'time' referenced before assignment

配置文件
# Config

MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'lnmp.org'
MYSQL_DB = 'sspanel'

MANAGE_PASS = 'passwd'
# if you want manage in other server you should set this value to global ip

MANAGE_BIND_IP = '127.0.0.1'
# make sure this port is idle

MANAGE_PORT = 15000

PANEL_VERSION = 'V2' # V2 or V3. V2 not support API
API_URL = 'http://vps.demo/mu'
API_PASS = 'mupass'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600
# BIND IP
# if you want bind ipv4 and ipv6 '[::]'
# if you want bind all of ipv4 if '0.0.0.0'
# if you want bind all of if only '4.4.4.4'

SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'rc4-md5'
# LOG CONFIG

LOG_ENABLE = False
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'

**Comment by RyanRong** [comment]
同样遇到此问题 环境是 centos 7 x64 vultr vps

**Comment by zuoruizhi** [comment]
python版本多少

**Comment by RyanRong** [comment]
Python 2.7.5 (default, Aug 18 2016, 15:58:25) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2

**Comment by floyd-li** [comment]
同遇到此问题，DEBIAN 7 X32，DigitalOcean VPS

**Comment by RyanRong** [comment]
这个bug，需要作者重新push了。_

**Comment by crazygold** [comment]
@RyanRong 测试正常

**Comment by mengskysama** [comment]
是不是用了v3的接口，可能会有问题现在修掉了。这个合并我没有测试过。

**Comment by zuoruizhi** [comment]
@mengskysama V2的 已经复现   V3的还有一个pull需要merged

**Comment by RyanRong** [comment]
@mengskysama 并没有用什么接口。

**Comment by mengskysama** [comment]
@zuoruizhi 哪个pr，我没有看到

**Comment by zuoruizhi** [comment]
#58

**Comment by mengskysama** [comment]
@zuoruizhi thanks done!

**Comment by zuoruizhi** [comment]
@mengskysama #59 fix

**Comment by zuoruizhi** [comment]
@RyanRong 着急先自己改下吧

**Comment by ILoveMoneyAndGirl** [comment]
xx

**Comment by ILoveMoneyAndGirl** [comment]
@zuoruizhi 
配置完了，但是翻不了墙，以下是我的配置文件及日志，麻烦帮我看看，配置是否有误。
import logging

#Config
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'ss'
MYSQL_PASS = '152535455565'
MYSQL_DB = 'ss2vpn'

MANAGE_PASS = 'ss'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://www.ss2vpn.store/mu'
API_PASS = 'ss'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600

#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'rc4-md5'

#LOG CONFIG
LOG_ENABLE =True
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'
---------------------------------------sspanel---------------------------------------
//  ss-panel v3 配置
//
// !!! 修改此key为随机字符串确保网站安全 !!!
key = 'ss2vpn'
env = 'prod'  // 正式环境请保持env为prod确保安全
debug =  'false'  //  正式环境请确保为false
appName = 'ss-panel3'             //站点名称
baseUrl = 'http://www.ss2vpn.store'            // 站点地址
timeZone = 'PRC'        // RPC 天朝时间  UTC 格林时间
pwdMethod = 'md5'       // 密码加密   可选 md5,sha256
salt = ''               // 密码加密用，从旧版升级请留空
theme    = 'default'   // 主题
// v3.4 后使用 session代替authDriver
// session,cache  可选 file/redis
session = 'file'
cache   = 'file'
tokenDriver = 'db'
// mu key 用于校验ss-go mu的请求
muKey = 'ss'
// 邮件
mailDriver = 'mailgun'   // mailgun   #smtp不在支持,仅供测试

// 注册限制,每天每个ip能注册的次数
ipDayLimit = '10'

// 邮箱验证设置
emailVerifyEnabled = 'false' // 是否开启注册时邮箱验证 (true:开启 false:关闭)
emailVerifyCodeLength = '8'  // 邮箱验证代码长度
emailVerifyTTL = '30'        // 验证代码有效时间 单位分钟

// 用户签到设置
checkinTime = '22'      // 签到间隔时间 单位小时
checkinMin = '93'       // 签到最少流量 单位MB
checkinMax = '97'       // 签到最多流量

//
defaultTraffic = '5'      // 用户初始流量 单位GB
// 注册后获得的邀请码数量
inviteNum = '5'

// 记录流量日志到dynamodb ,beta,请勿开启
log_traffic_dynamodb = 'false'

# database 数据库配置

db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'ss2vpn'
db_username = 'ss'
db_password = '152535455565'
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''

# redis

redis_scheme = 'tcp'
redis_host = '127.0.0.1'
redis_port = '6379'
redis_database = '0'
redis_pass = ''

# mailgun

mailgun_key = ''
mailgun_domain = ''
mailgun_sender = ''

# smtp

smtp_host = ''
smtp_username = ''
smtp_port = ''
smtp_name = ''
smtp_sender = ''
smtp_passsword = ''
smtp_ssl = 'true'

# aws

aws_access_key_id = ''
aws_secret_access_key = ''
aws_region = 'ap-northeast-1'
aws_ses_region = 'us-east-1'
aws_ses_sender = ''
///////////////////////////////log//////////////////////
2016, Oct 01 Sat 15:48:49 eventloop.py[line:251] DEBUG using event model: epoll
2016, Oct 01 Sat 15:48:50 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:48:50 dbtransfer.py[line:176] INFO db start server at port [1025] pass [L1wrxc]
2016, Oct 01 Sat 15:48:50 manager.py[line:86] INFO adding server at 0.0.0.0:1025
2016, Oct 01 Sat 15:48:50 dbtransfer.py[line:176] INFO db start server at port [1026] pass [T6vN8Z]
2016, Oct 01 Sat 15:48:50 manager.py[line:86] INFO adding server at 0.0.0.0:1026
2016, Oct 01 Sat 15:48:51 dbtransfer.py[line:205] INFO db loop2
2016, Oct 01 Sat 15:48:53 dbtransfer.py[line:121] INFO http://www.ss2vpn.store/mu/nodes/1/online_count?key=ss2vpn - count=0 - {"ret":1,"msg":"ok"}
2016, Oct 01 Sat 15:48:55 dbtransfer.py[line:138] INFO http://www.ss2vpn.store/mu/nodes/1/info?key=ss2vpn - load=0.00+0.00+0.00+3%2F172+4098&uptime=101.25 - {"ret":1,"msg":"ok"}
2016, Oct 01 Sat 15:49:05 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:49:21 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:49:36 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:49:51 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:50:06 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:50:21 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:50:36 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:50:51 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:51:06 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:51:22 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:51:37 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:51:52 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:52:07 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:52:22 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:52:37 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:52:52 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:53:07 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:53:22 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:53:38 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:53:53 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:54:08 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:54:23 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:54:38 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:54:53 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:55:08 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:55:23 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:55:39 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:55:54 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:56:09 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:56:24 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:56:39 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:56:54 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:57:09 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:57:24 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:57:39 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:57:55 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:58:10 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:58:25 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:58:40 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:58:55 dbtransfer.py[line:205] INFO db loop2
2016, Oct 01 Sat 15:58:55 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:58:55 dbtransfer.py[line:121] INFO http://www.ss2vpn.store/mu/nodes/1/online_count?key=ss2vpn - count=0 - {"ret":1,"msg":"ok"}
2016, Oct 01 Sat 15:58:56 dbtransfer.py[line:138] INFO http://www.ss2vpn.store/mu/nodes/1/info?key=ss2vpn - load=0.02+0.01+0.00+3%2F168+4180&uptime=703.67 - {"ret":1,"msg":"ok"}
2016, Oct 01 Sat 15:59:10 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:59:25 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:59:40 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 15:59:56 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:00:11 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:00:26 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:00:41 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:00:56 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:01:11 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:01:26 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:01:41 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:01:56 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:02:12 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:02:27 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:02:42 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:02:57 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:03:12 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:03:27 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:03:42 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:03:57 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:04:13 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:04:28 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:04:43 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:04:58 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:05:13 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:05:28 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:05:43 dbtransfer.py[line:187] INFO db loop
2016, Oct 01 Sat 16:05:58 dbtransfer.py[line:187] INFO db loop

**Comment by zuoruizhi** [comment]
没有问题    把防火墙关了再看下

**Comment by ILoveMoneyAndGirl** [comment]
如果没有来自你的 IP 的 TCP 连接的话，那八成就是防火墙的锅了，执行 iptables 放行你的端口：

$ iptables -I INPUT -p tcp -m tcp --dport 你的端口 -j ACCEPT
$ iptables-save   你的端口，是指？

**Comment by zuoruizhi** [comment]
正常啊   我用你的服务器能上啊
![image](https://cloud.githubusercontent.com/assets/8614920/19012807/37ffb7ea-87f2-11e6-9839-9f29fda4125c.png)

**Comment by zuoruizhi** [comment]
[WinMTR.zip](https://github.com/mengskysama/shadowsocks-rm/files/504173/WinMTR.zip)
你看下你和服务器连接吧    看下丢包率

**Comment by ILoveMoneyAndGirl** [comment]
耶，你木有密码是怎么用的？

**Comment by zuoruizhi** [comment]
你发配置文件和日志时候全发出来了

**Comment by ILoveMoneyAndGirl** [comment]
不行，我是mac的电脑。应该不是丢包吧。那些发出来的配置，密码我是改过的。你看到密码是多少，我要改下
<img width="515" alt="vv" src="https://cloud.githubusercontent.com/assets/6365625/19012850/552b9c2a-87f3-11e6-85db-89870e838e1e.png"> 我用着是这种方式连接

**Comment by zuoruizhi** [comment]
所有用户的密码都要改，MAC客户端不知道咋用，询问下客户端那边吧，我是用的openwrt的

**Comment by ILoveMoneyAndGirl** [comment]
SYNCTIME = 600 这个是指流量结算时间？单位秒？

**Comment by zuoruizhi** [comment]
恩

**Comment by ILoveMoneyAndGirl** [comment]
ok，谢谢。我在看下，既然你没问题，应该服务器的搭建，是木有问题，可能是客服端配置错误。谢谢咯~

**Comment by ILoveMoneyAndGirl** [comment]
还是不行，我用windows系统也测试了。看到日志有这个报错：
2016, Oct 01 Sat 17:10:43 eventloop.py[line:251] DEBUG using event model: epoll
2016, Oct 01 Sat 17:10:43 manager.py[line:65] ERROR [Errno 98] Address already in use
2016, Oct 01 Sat 17:10:43 manager.py[line:66] ERROR can not bind to manager address
 //你能看出点端倪吗？

**Comment by ILoveMoneyAndGirl** [comment]
我刚注册的账号，拿来使用，也报这个错误，地址应该不会已被使用啊

**Comment by zuoruizhi** [comment]
你运行了几遍，端口被占用了，会kill就把运行的都关掉，重新运行，不会就直接reboot 服务器

**Comment by ILoveMoneyAndGirl** [comment]
ok

**Comment by ILoveMoneyAndGirl** [comment]
我还是无法使用。麻烦你试试     "server": "www.ss2vpn.store",
    "server_port": 1027,
    "password": "MLZExA",
    "method": "rc4-md5" 能够使用吗，不知道什么原因、

**Comment by zuoruizhi** [comment]
完全正常，你把域名换成ip试试，然后测下mtr

**Comment by ILoveMoneyAndGirl** [comment]
mtr 是什么？我菜鸟。呜呜。。。

**Comment by zuoruizhi** [comment]
看前面我发的软件

**Comment by ILoveMoneyAndGirl** [comment]
哦哦。好的~~，我找个windows电脑试试

**Comment by vinqon** [comment]
我也遇到这个问题，Mac连不上，iPhone可以，@cuidaohan 有找到原因吗？

**Comment by vinqon** [comment]
囧，确实是我Mac本地网络问题
