### ISSUE TITLE
在执行python时无任何反应

### ISSUE THREAD

**Issue by leewaiho** [mengskysama/shadowsocks-rm#61]
执行时无反应 终止时给出如下信息
^CTraceback (most recent call last):
  File "servers.py", line 63, in <module>
    main()
  File "servers.py", line 59, in main
    time.sleep(100)
KeyboardInterrupt

**Comment by zuoruizhi** [comment]
正常

**Comment by zuoruizhi** [comment]
运行姿势不对 python servers.py &
要放在后台运行 正常运行程序时啥输出都没有的，都输出到日志了

**Comment by leewaiho** [comment]
@zuoruizhi 可是连  root:db loop 都没有哦

**Comment by zuoruizhi** [comment]
你看日志了吗

**Comment by LeeWaiHo** [comment]
看了...
2016, Sep 25 Sun 15:44:21 dbtransfer.py[line:187] INFO db loop
2016, Sep 25 Sun 15:44:21 dbtransfer.py[line:176] INFO db start server at port [1025] pass [gfIOqx]
2016, Sep 25 Sun 15:44:21 manager.py[line:86] INFO adding server at 0.0.0.0:1025
2016, Sep 25 Sun 15:44:21 dbtransfer.py[line:176] INFO db start server at port [50000] pass [0000000]
2016, Sep 25 Sun 15:44:21 manager.py[line:86] INFO adding server at 0.0.0.0:50000
2016, Sep 25 Sun 15:44:21 dbtransfer.py[line:176] INFO db start server at port [50001] pass [Ue0n0h]
2016, Sep 25 Sun 15:44:21 manager.py[line:86] INFO adding server at 0.0.0.0:50001
2016, Sep 25 Sun 15:44:22 dbtransfer.py[line:205] INFO db loop2
可是用客户端还是无法建立连接..iptables 也添加了端口..

**Comment by leewaiho** [comment]
@zuoruizhi 可以了 谢谢你的热心帮助!!

**Comment by lzhui** [comment]
怎么解决的啊，我遇到同样的问题了@LeeWaiHo

**Comment by leewaiho** [comment]
@lzhui  python servers.py & 之后就可以了 它已经在后台运行了的
