### ISSUE TITLE
问题：No JSON object could be decoded

### ISSUE THREAD

**Issue by ghost** [mengskysama/shadowsocks-rm#70]
和sspanelv3在同一台一号节点服务器上的manyuser可以用
但是另外一个二号节点服务器上的manyuser不能用
连接都蛮正常的，log里能看到连接上了数据库
在sspanel里添加了二号节点，但是在线人数产生流量负载什么的都没有数据。

**执行之后：**
[root@RS shadowsocks]# python servers.py

没报错
**但是客户端访问网页的时候：**
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 207, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 59, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 49, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 190, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 160, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

求大神！

**Comment by zuoruizhi** [comment]
第二台管理端口有问题，重启下服务器

**Comment by ghost** [comment]
重启过了…还是不行
什么叫第二台管理端口有问题啊…不太明白

**Comment by zuoruizhi** [comment]
上配置文件

**Comment by ghost** [comment]
#manyuser配置
import logging

#Config
MYSQL_HOST = '45.76.XX.XX'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'sqlpass'
MYSQL_DB = 'sspanel'

MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://vpn.abc.pw/mu'
API_PASS = 'ssmu'
NODE_ID = '2'
CHECKTIME = 15
SYNCTIME = 600

#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'aes-256-cfb'

#LOG CONFIG
LOG_ENABLE = True
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'



//  ss-panel v3 配置
//
// !!! 修改此key为随机字符串确保网站安全 !!!
key = '123'
env = 'prod'  // 正式环境请保持env为prod确保安全
debug =  'false'  //  正式环境请确保为false
appName = 'abc'             //站点名称
baseUrl = 'http://vpn.abc.pw'            // 站点地址
timeZone = 'PRC'        // RPC 天朝时间  UTC 格林时间
pwdMethod = 'md5'	// 密码加密   可选 md5,sha256
salt = ''               // 密码加密用，从旧版升级请留空
theme    = 'default'   // 主题
// v3.4 后使用 session代替authDriver
// session,cache  可选 file/redis
session = 'file'
cache   = 'file'
tokenDriver = 'db'
// mu key 用于校验ss-go mu的请求
muKey = 'ssmu'
// 邮件
mailDriver = 'mailgun'   // mailgun   #smtp不在支持,仅供测试

// 注册限制,每天每个ip能注册的次数
ipDayLimit = '4'

// 邮箱验证设置
emailVerifyEnabled = 'false' // 是否开启注册时邮箱验证 (true:开启 false:关闭)
emailVerifyCodeLength = '8'  // 邮箱验证代码长度
emailVerifyTTL = '30'        // 验证代码有效时间 单位分钟

// 用户签到设置
checkinTime = '24'	// 签到间隔时间 单位小时
checkinMin = '50'	// 签到最少流量 单位MB
checkinMax = '150'	 // 签到最多流量

//
defaultTraffic = '5'	  // 用户初始流量 单位GB
// 注册后获得的邀请码数量
inviteNum = '0'

// 记录流量日志到dynamodb ,beta,请勿开启


log_traffic_dynamodb = 'false'

# database 数据库配置
db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'sspanel'
db_username = 'root'
db_password = 'sqlpass'
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''

# redis
redis_scheme = 'tcp'
redis_host = '127.0.0.1'
redis_port = '6379'
redis_database = '0'
redis_pass = ''

# mailgun
mailgun_key = ''
mailgun_domain = ''
mailgun_sender = ''

# smtp
smtp_host = ''
smtp_username = ''

**Comment by ghost** [comment]
我之前没改NODE_ID，刚刚上配置文件的时候才发现，已改正…现在改了之后sspanel可以显示在线人数负载什么的了，但是产生流量还是暂无数据，ss还是用不了

**Comment by zuoruizhi** [comment]
netstat -lanp|grep python

ps aux | grep python

**Comment by ghost** [comment]
[root@RS ~]# netstat -lanp|grep python
tcp        0      0 0.0.0.0:10044               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10015               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10048               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10018               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10051               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10023               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10056               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10057               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10025               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10029               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10000               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10034               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10004               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10005               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10038               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10006               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10040               0.0.0.0:*                   LISTEN      1670/python         
tcp        0      0 0.0.0.0:10011               0.0.0.0:*                   LISTEN      1670/python         
udp        0      0 0.0.0.0:10000               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10004               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10005               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10006               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10011               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10015               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10018               0.0.0.0:*                               1670/python         
udp        0      0 127.0.0.1:23333             0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10023               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10025               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10029               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10034               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10038               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10040               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10044               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10048               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10051               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10056               0.0.0.0:*                               1670/python         
udp        0      0 0.0.0.0:10057               0.0.0.0:*                               1670/python         
[root@RS ~]# ps aux | grep python
root      1670  0.0  1.8 427768 13924 pts/1    Sl+  06:35   0:18 python servers.py
root      6848  0.0  0.1 103312   876 pts/0    S+   13:25   0:00 grep python

**Comment by zuoruizhi** [comment]
没啥问题啊        用户连一下试试

**Comment by ghost** [comment]
"无法访问此网站"
……
刚刚又看了一下servers.py的运行情况，显示了这些
[root@RS ~]# screen -r ss

  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 62, in __init__
    self.__recv_packet()
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 81, in __recv_packet
    packet_header = self.__recv_from_socket(4)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 74, in __recv_from_socket
    raise OperationalError(2013, "Lost connection to MySQL server during query")
OperationalError: (2013, 'Lost connection to MySQL server during query')
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 189, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 147, in pull_db_all_user
    passwd=config.MYSQL_PASS, db=config.MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 258, in __init__
    self.commit()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 292, in commit
    self.errorhandler(None, exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

**Comment by ghost** [comment]
我升级一下python版本到2.7试试
一号服务器用的centos7，自带2.7
这个好像是以前建的centos6，所以python版本低了点

**Comment by ghost** [comment]
升级之后还是不行。。
现在python是2.7.5的了

**Comment by zuoruizhi** [comment]
你最后的报错是没连上mysql

**Comment by ghost** [comment]
啊啊啊啊啊好了！！！升级python之后理论就可用了
刚刚只是忘记允许防火墙通过了
谢谢谢谢！

**Comment by zuoruizhi** [comment]
上log吧，全部的

**Comment by ghost** [comment]
2017, Jan 14 Sat 02:30:17 asyncdns.py[line:402] DEBUG resolving www.google.co.jp with type 1 using server 108.61.10.10
2017, Jan 14 Sat 02:30:30 dbtransfer.py[line:187] INFO db loop
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:692] DEBUG destroy: ssl.gstatic.com:443
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:696] DEBUG destroying remote
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:702] DEBUG destroying local
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:692] DEBUG destroy: www.google.co.jp:443
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:696] DEBUG destroying remote
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:702] DEBUG destroying local
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:692] DEBUG destroy: www.google.com:443
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:696] DEBUG destroying remote
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:702] DEBUG destroying local
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:692] DEBUG destroy: www.google.com:443
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:696] DEBUG destroying remote
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:702] DEBUG destroying local
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:692] DEBUG destroy: www.gstatic.com:443
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:696] DEBUG destroying remote
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:702] DEBUG destroying local
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:692] DEBUG destroy: www.google.com:443
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:696] DEBUG destroying remote
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:702] DEBUG destroying local
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:833] DEBUG accept
2017, Jan 14 Sat 02:30:39 tcprelay.py[line:332] INFO connecting clients4.google.com:443 from 223.72.88.194:14609
2017, Jan 14 Sat 02:30:39 asyncdns.py[line:417] DEBUG hit cache: clients4.google.com

ok啦
再次感谢@zuoruizhi，很负责！
