### ISSUE TITLE
配合orvice/ss-panel使用时，出现HTTP ERROR 401的错误

### ISSUE THREAD

**Issue by prncoprs** [mengskysama/shadowsocks-rm#76]
Ubuntu版本：16.04 LTS 64bits
python版本：Python 2.7.12
mysql版本：Ver 14.14 Distrib 5.7.17, for Linux (x86_64)
nginx版本：nginx/1.10.0 (Ubuntu)
php版本：PHP 7.0.15-0ubuntu0.16.04.2 (cli) ( NTS )
使用的ss-panel版本为：orvice/ss-panel master（昨天clone下来的）
shadowsocks后端版本：mengskysama/shadowsocks-rm（昨天clone下来的）

**nginx的站点配置信息**：
```
server {                                            
	listen 80 default_server;
	listen [::]:80 default_server;
	
	#root /var/www/html;
	root /var/www/ss-panel/public;
	#root /var/www/shadowsocks-panel/Public;
	
	# Add index.php to the list if you are using PHP
	#index index.html index.htm index.nginx-debian.html index.php;
	index index.html index.htm index.php;
	
	server_name _;
	
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		#try_files $uri $uri/ =404;
		try_files $uri $uri/ /index.php$is_args$args;
	}
    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
    #
    #   # With php7.0-cgi alone:
    #   fastcgi_pass 127.0.0.1:9000;
    #   # With php7.0-fpm:
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
}
```

**ss-panel的.env配置信息**：
```
//  ss-panel v3 配置                                                       
//
// !!! 修改此key为随机字符串确保网站安全 !!!
key = 'sspanel'
env = 'prod'  // 正式环境请保持env为prod确保安全
debug =  'true'  //  正式环境请确保为false
appName = 'ss-panel3'             //站点名称
baseUrl = 'https://www.google.com'            // 站点地址
timeZone = 'PRC'        // RPC 天朝时间  UTC 格林时间
pwdMethod = 'sha256'       // 密码加密   可选 md5,sha256
salt = ''               // 密码加密用，从旧版升级请留空
theme    = 'default'   // 主题
// v3.4 后使用 session代替authDriver
// session,cache  可选 file/redis
session = 'file'
cache   = 'file'
tokenDriver = 'db'
// mu key 用于校验ss-go mu的请求
muKey = ''
// 邮件
mailDriver = 'mailgun'   // mailgun   #smtp不在支持,仅供测试
// database 数据库配置
db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'sspanel'
db_username = 'sspanel'
db_password = 'sspanel'
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''
```
**shadowsocks-rm的config.py配置信息**：                                                                                                                  
```
#Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'sspanel'
MYSQL_PASS = 'sspanel'
MYSQL_DB = 'sspanel'

MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://139.XXX.XXX.XXX/mu' # IP has been shielded.  : )
API_PASS = 'sspanel'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600

#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'aes-256-cfb'

#LOG CONFIG
LOG_ENABLE = True
LOG_LEVEL = logging.NOTSET
#LOG_FILE = '/var/log/shadowsocks.log'
LOG_FILE = '/dev/stdout'
```

**python servers.py时的出错信息**：

```
root@ubuntu:~/shadowsocks-rm/shadowsocks# python servers.py 
2017, Mar 02 Thu 09:03:02 eventloop.py[line:251] DEBUG using event model: epoll
2017, Mar 02 Thu 09:03:03 dbtransfer.py[line:188] INFO db loop
2017, Mar 02 Thu 09:03:03 dbtransfer.py[line:177] INFO db start server at port [1025] pass [CuiqNP]
2017, Mar 02 Thu 09:03:03 manager.py[line:86] INFO adding server at 0.0.0.0:1025
2017, Mar 02 Thu 09:03:04 dbtransfer.py[line:206] INFO db loop2
2017, Mar 02 Thu 09:03:04 dbtransfer.py[line:117] INFO url: http://139.XXX.XXX.XXX/mu/nodes/1/online_count?key=sspanel   data: {'count': 0} 
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 208, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 120, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
2017, Mar 02 Thu 09:03:04 dbtransfer.py[line:212] WARNING db thread except:HTTP Error 401: Unauthorized
^CTraceback (most recent call last):
  File "servers.py", line 63, in <module>
    main()
  File "servers.py", line 59, in main
    time.sleep(100)
KeyboardInterrupt
```
请问可以帮忙定位一下问题在哪里吗？是我哪里没有配置好吗？
而且在ss-panel中添加站点的时候也会出现错误500，和这里有关吗？

**Comment by zuoruizhi** [comment]
看wiki，500没关系

**Comment by zuoruizhi** [comment]
https://github.com/mengskysama/shadowsocks-rm/wiki/关于mu-API-V1版本配置说明

**Comment by prncoprs** [comment]
⊙﹏⊙b汗！
我看muKey说的是Go做的后端，所以我一直以为是用的key。。。
