### ISSUE TITLE
在同步用户信息的时候报错

### ISSUE THREAD

**Issue by yanaex** [mengskysama/shadowsocks-rm#83]
Unhandled exception in thread started by <function run at 0x7ffbf370c500>
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/manager.py", line 218, in run
    Manager(config).run()
  File "/root/shadowsocks-rm/shadowsocks/manager.py", line 214, in run
    self._loop.run()
  File "../shadowsocks/eventloop.py", line 304, in run
    handler.handle_event(sock, fd, event)
  File "../shadowsocks/tcprelay.py", line 837, in handle_event
    self._dns_resolver, self._is_local)
  File "../shadowsocks/tcprelay.py", line 125, in __init__
    config['method'])
  File "../shadowsocks/encrypt.py", line 84, in __init__
    random_string(self._method_info[1]))
  File "../shadowsocks/encrypt.py", line 110, in get_cipher
    return m[2](method, key, iv, op)
  File "../shadowsocks/crypto/sodium.py", line 62, in __init__
    load_libsodium()
  File "../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
WARNING:root:send_command response
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 153, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 113, in del_server_out_of_bound_safe
    server = json.loads(DbTransfer.get_instance().send_command('stat: {"server_port":%s}' % row[0]))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
WARNING:root:db thread except:No JSON object could be decoded
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 151, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 59, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 49, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
WARNING:root:db thread except:timed out
stop
^CTraceback (most recent call last):
  File "servers.py", line 61, in <module>
    main()
  File "servers.py", line 57, in main
    time.sleep(100)

并且无法使用

**Comment by zuoruizhi** [comment]
前端环境是否有调整

**Comment by zuoruizhi** [comment]
Sorry ，看错了。跟前端暂时没啥关系。看样子是管理线程崩了，重启下吧

**Comment by yanaex** [comment]
目前换成CentOS正常...之前是大便
